### PR TITLE
modern business

### PR DESCRIPTION
**Pull request by jwu-au**
The **Modern Business** Theme:

https://startbootstrap.com/templates/modern-business/

modern-business

### CODE REVIEW

**Comment by jwu-au** [comment]
@hishamco 
new PR. As per discussion in https://github.com/OrchardCoreContrib/OrchardCoreContrib.Themes/pull/1
:)

**Comment by hishamco** [comment]
You can rebase on the previous one ;) no problem @jwu-au, I tested the previous one, the layout was miss some style files, perhaps there 're something happen, I will check this now and merge

Thanks

**Comment by hishamco** [comment]
Just remove the following files before I merge `LICENSE`, `.gitignore`, `.gitattributes` coz there 're no longer used. Also why I'm getting 404 for `modern-business.css` and `modern-business.js`?!!



I will add a link to your original repo if you prefer to add enhancement there, but I'm glad to keep this updated if you have a time

**Comment by hishamco** [comment]
Header

**Comment by hishamco** [comment]
Also you could remove the ItemGroup in `.csproj` except the one for package reference

**Comment by jwu-au** [comment]
Fixed the 404 as I didn't commit files in wwwroot folders, my bad.
In regard to the ItemGroup in .csproj, it has similar content as other buildin themes in OrchardCore. And also the wwwroot folder contains the original theme files which are not necessary for orchard, and should be excluded as EmbeddedResource. Are you sure we don't want these ItemGroups ?

**Comment by hishamco** [comment]
Also you could remove the ItemGroup in `.csproj` except the one for package reference

**Comment by jwu-au** [comment]
@hishamco It's all good now.

**Comment by hishamco** [comment]
LGTM 🚀 🚀 🚀

**Comment by hishamco** [comment]
Thanks a lot @jwu-au, I appreciate your efforts

**Comment by jwu-au** [comment]
@hishamco no worries, thanks for your help too.

**Comment by hishamco** [comment]
FYI I'm getting some security alerts on the repo, so you can check the PRs created, I will remove the unnecessary files, coz I think you forgot to remove the original template from `wwwroot`

**Comment by jwu-au** [comment]
@hishamco good to clean up. `contact_me.js` and `jqBootstrapValidation.js` in `js` folder can also removed.

**Pull request merged**
