### PR TITLE
added modern business theme

### PR DESCRIPTION
**Pull request by jwu-au**

### CODE REVIEW

**Comment by hishamco** [comment]
@jwu-au thanks for your contribution, could please add a snapshot for your theme, also we need to add a reference to the `OrchardCoreContrib.Themes.Web` so anyone can see it in action

I think I need to update the `README.md` for the last step

**Comment by jwu-au** [comment]
@hishamco Is the **Theme.png** in wwwroot folder the snapshot you're looking for?
I'll add the reference in web project.

**Comment by jwu-au** [comment]
I might missed understood the **src** folder you refer to. In the PR, I actually placed a physical **src** folder in the source control, and the theme folder under it. Or do you mean the virtual src folder in VS? Please clarify.

**Comment by hishamco** [comment]
> the snapshot you're looking for?

Just a snapshot of how the theme is look like, paste it here

>  I actually placed a physical src folder in the source control, and the theme folder under it. Or do you mean the virtual src folder in VS

Please add it in both

**Comment by jwu-au** [comment]
The original theme template will be: https://startbootstrap.com/templates/modern-business/

Snapshot:
alt text

**Comment by jwu-au** [comment]
Changes made:
* Updated reference to latest preview **1.0.0-rc1-13334**, the theme is built on top of the latest dev branch, it won't work with RC1. As RC2 is coming soon or later, this shouldn't be a big issue, right?
* As the project/assembly name of theme is changed to **OrchardCoreContrib.Themes.ModernBusiness**, I ended up to changed some paths in Layout file so it can locate the resources. The original name of theme is called **TheModernBusinessTheme**.

Other than above, the theme is setup successfully via receipt and running ok.
 
@hishamco for you to review and test.

**Comment by hishamco** [comment]
Nah, seems I did something wrong with the project skeleton, I will fix it on this repo, then you can rebase after I check your theme

Thanks

**Comment by hishamco** [comment]
@jwu-au please rebase on the dev, BTW I don't think we need to add a folder for each theme, just add it directly on the `src` folder

Sorry for my bad, I didn't realize that I made a mistake on the project skeleton until I saw your PR

Thanks again

**Comment by hishamco** [comment]
@jwu-au please rebase on the dev, BTW I don't think we need to add a folder for each theme, just add it directly on the `src` folder

Sorry for my bad, I didn't realize that I made a mistake on the project skeleton until I saw your PR

Thanks again

**Pull request closed without merging**
